Fix Display Issue for Long Customer Names/Emails in Payment Request Details Modal
nofrixion/nofrixion.business pull request #106
Opened 2023-10-09 18:13 UTC by Publicker

This pull request addresses a UI issue in the Payment Request Details modal. Previously, long customer names or emails would cause the QR code to be compressed, rendering it nearly illegible. With this fix, long customer names and emails are now displayed appropriately without affecting the QR code's size or readability.

2023-10-09 18:14 UTC, sipsorcery approved these changes

2023-10-09 18:17 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/106.

2023-10-10 06:44 UTC, donalnofrixion approved these changes

2023-10-10 08:53 UTC, arifmatin approved these changes

2023-10-10 11:57 UTC, sauravmaiti22 approved these changes

2023-10-10 12:39 UTC, pabloi-nf requested changes
I works well, but we can improve the spacing by changing the line-height of the name to 28px (1.75rem) and a separation of 0.5rem between the name and the email

2023-10-10 15:10 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/106.

2023-10-10 15:18 UTC, merged