Added paid column
nofrixion/nofrixion.business pull request #113
Opened 2023-10-12 13:50 UTC by sauravmaiti22

Added paid column to payment requests table.

2023-10-12 13:55 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/113.

2023-10-12 14:30 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/113.

2023-10-13 11:35 UTC, Publicker requested changes

2023-10-13 11:35 UTC, Publicker commented on packages/components/src/components/ui/PaymentRequestRow/PaymentRequestRow.tsx
> +                  'text-[#73808C]': amountPaid === 0,
This could be changed for `text-grey-text`

2023-10-13 11:35 UTC, Publicker commented on packages/components/src/components/ui/TransactionsTooltip/TransactionsTooltip.tsx
> +  side = 'top',
Based on Figma preview, I think the preferred Tooltip side is bottom, can we change the default one to bottom?

2023-10-13 11:35 UTC, Publicker commented on packages/components/src/components/ui/TransactionsTooltip/TransactionsTooltip.tsx
> +                            className={cn('pr-2 text-[#454D54]', {
This could also be changed to `text-control-grey-hover`

2023-10-13 11:35 UTC, Publicker commented on packages/components/src/components/ui/TransactionsTooltip/TransactionsTooltip.tsx
> +                            className={cn('text-xs text-[#73808C] pr-12', {
Same here, `text-grey-text`

2023-10-13 11:35 UTC, Publicker commented on packages/components/src/components/ui/TransactionsTooltip/TransactionsTooltip.tsx
> +                              'text-sm tabular-nums text-[#00264D] font-medium text-right',
This is `text-default-text`

2023-10-13 11:35 UTC, Publicker commented on packages/components/src/components/ui/TransactionsTooltip/TransactionsTooltip.tsx
> +                                'text-[#73808C]':
This is `grey-text`

2023-10-13 11:35 UTC, Publicker commented on packages/components/src/components/ui/TransactionsTooltip/TransactionsTooltip.tsx
> +                            <span className={cn({ 'text-[#F32448]': paymentAttempt.isRefund })}>
This is `text-negative-red`

2023-10-13 11:35 UTC, Publicker commented on packages/components/src/components/ui/atoms/Icon/Icon.tsx
We do not include stroke colours in here but rather in the usage, as it gives us more control over it. Also none of stroke properties, such as strokeLinecap and strokeLinejoin

2023-10-13 11:35 UTC, Publicker commented on packages/components/src/components/ui/molecules/Status/Status.tsx
> +      overpaid: ['text-[#29A37A]'],
This is `text-positive-green`

2023-10-13 11:35 UTC, Publicker commented on packages/components/src/components/ui/molecules/Status/Status.tsx
> +  authorized: {
I'd try to keep the name convention to `authorised` rather than `authoriZed` (see line 120)

2023-10-13 11:35 UTC, Publicker commented on packages/components/src/types/LocalTypes.ts
> +  wallet?: LocalWallets | undefined
No need of `| undefined` if property already has `?`

2023-10-13 11:51 UTC, Publicker commented
I noticed a couple of things:

- The skeleton of the new 'Paid' column seems slightly larger than its actual content. It might look better if it was narrowed down a bit, so it matches the content's width post-loading. Check out this image for reference: 
<img width="1618" alt="Screenshot 2023-10-13 at 08 23 37" src="https://github.com/nofrixion/nofrixion.business/assets/52673485/b260e4bd-b70f-4b96-b416-59de961bae62">

- We already had some minor responsive glitches because of the new Payment attempts column. This PR, however, introduces some others. I made a video showing the table extending beyond its designated space (the white area) as the screen resizes.

https://github.com/nofrixion/nofrixion.business/assets/52673485/bb1610f0-f307-4bfd-851c-f3b7084f6eef

2023-10-13 12:32 UTC, pabloi-nf requested changes
- The tooltip should appear under the number, not on top.
- The label for partially paid PRs should say now "Partly paid", both on the table and the filter tab.

2023-10-13 12:41 UTC, sauravmaiti22 commented on packages/components/src/components/ui/molecules/Status/Status.tsx
> +  authorized: {
This authorized is different than authorise payout which is recently changed from approve. I agree we need to correct the spelling, but that has to be another story where it is changed everywhere.

2023-10-13 12:43 UTC, Publicker commented on packages/components/src/components/ui/molecules/Status/Status.tsx
> +  authorized: {
Ah! Got it.
Thanks

2023-10-13 14:50 UTC, sauravmaiti22 commented
> I noticed a couple of things:
> 
> * The skeleton of the new 'Paid' column seems slightly larger than its actual content. It might look better if it was narrowed down a bit, so it matches the content's width post-loading. Check out this image for reference:
> 
> <img alt="Screenshot 2023-10-13 at 08 23 37" width="1618" src="https://user-images.githubusercontent.com/52673485/274891950-b260e4bd-b70f-4b96-b416-59de961bae62.png">
> * We already had some minor responsive glitches because of the new Payment attempts column. This PR, however, introduces some others. I made a video showing the table extending beyond its designated space (the white area) as the screen resizes.
> 
>  113.Responsive.issues.mp4

@Publicker Fixed responsiveness to a large extent. Only for a very small period you don't see the tags for some reason. Maybe we can create a bug for that.

2023-10-13 14:54 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/113.

2023-10-13 15:23 UTC, sauravmaiti22 commented
> * The tooltip should appear under the number, not on top.
> * The label for partially paid PRs should say now "Partly paid", both on the table and the filter tab.

@pabloi-nf Fixed the first comment and created a story for the second one.

2023-10-13 15:23 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/113.

2023-10-16 10:12 UTC, Publicker requested changes
Brilliant! Almost there, I've found just a few spots where we could opt for named colours instead of using their values directly.

2023-10-16 10:12 UTC, Publicker commented on packages/components/src/components/ui/PaymentRequestRow/PaymentRequestRow.tsx
> +                    'border-b-[0.094rem] border-dashed border-[#ABB2BA] pb-[0.125rem]':
```suggestion
                    'border-b-[0.094rem] border-dashed border-grey-highlighted pb-[0.125rem]':
```

2023-10-16 10:12 UTC, Publicker commented on packages/components/src/components/ui/PaymentRequestRow/PaymentRequestRow.tsx
> +            <span className="font-medium text-[#73808C]">
```suggestion
            <span className="font-medium text-grey-text">
```

2023-10-16 10:30 UTC, sauravmaiti22 commented on packages/components/src/components/ui/PaymentRequestRow/PaymentRequestRow.tsx
> +                    'border-b-[0.094rem] border-dashed border-[#ABB2BA] pb-[0.125rem]':
Done! it was border-border-grey-highlighted.

2023-10-16 10:34 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/113.

2023-10-16 10:35 UTC, Publicker commented on packages/components/src/components/ui/PaymentRequestRow/PaymentRequestRow.tsx
> +                    'border-b-[0.094rem] border-dashed border-[#ABB2BA] pb-[0.125rem]':
You're right! Good catch (too much copy-paste from my side 🤪)

2023-10-16 10:36 UTC, Publicker approved these changes

2023-10-16 11:50 UTC, pabloi-nf approved these changes

2023-10-16 11:52 UTC, merged