Added business banks to banks list
nofrixion/nofrixion.business pull request #119
Opened 2023-10-23 16:37 UTC by arifmatin

#MOOV-2358

2023-10-23 16:41 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/119.

2023-10-24 09:34 UTC, arifmatin commented on packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
> +      setBanks(bankList)
Yeah sure. The sort is there now.

2023-10-24 09:38 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/119.

2023-10-24 09:52 UTC, donalnofrixion requested changes
Can you take a look at onConnectBank in functional/CurrentAccountsList.tsx.
It might need updating/fixing

2023-10-24 10:09 UTC, arifmatin commented
@donalnofrixion Ah I see what you mean.

2023-10-24 12:44 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/119.

2023-10-24 14:49 UTC, donalnofrixion commented on packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
> +    // is set on the personalInstitutionID field for both personal and business.
Are all environments set up this way? If needs be can you create a script to update them?

2023-10-24 14:49 UTC, donalnofrixion approved these changes

2023-10-24 15:04 UTC, arifmatin commented on packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
> +    // is set on the personalInstitutionID field for both personal and business.
Sorry this comment may be misleading. In the database both personal and business is 1 record. I added a method that separates it to 2 records in mm4b. By the time it gets here, the records are separated, filtered and sorted. Therefore no change needs to made in onConnectBank method or the environments.

2023-10-24 15:18 UTC, merged