✨ [MOOV-2416]: Added Edit Payout functionality
nofrixion/nofrixion.business pull request #128
Opened 2023-11-03 01:19 UTC by agranillonf

Added functionality to the "Edit payout" button on the Payout Details modal.

2023-11-03 01:24 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/128.

2023-11-03 10:34 UTC, pabloi-nf requested changes
Looks good!

2 comments:
- I think the beneficiary should still be the predetermined one, and only allow the manually editing if the user requests it.
- We need to add a success toast message that confirms the changes weere made. "Changes applied"

2023-11-03 11:57 UTC, Publicker approved these changes

2023-11-03 18:15 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/128.

2023-11-03 20:23 UTC, agranillonf commented
@pabloi-nf Fixes have been applied.

2023-11-06 10:05 UTC, arifmatin approved these changes

2023-11-06 16:58 UTC, pabloi-nf requested changes
Thanks @agranillonf 

I can see it doesn't says anymore "Add manually", but it's not showing the beneficiary in the list either.
Is not possible to show it like this?:
<img width="481" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/f6ede84f-36f8-4d03-9301-1e2425c045c5">

Another thing is that when there are no changes made and the save button is pressed, the toast still says that changes were made.
We should use a disabled button if there are no changes.
Text color: #73808C
Background color: #E3E5E8

<img width="585" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/4da7956a-bbfa-4a6c-8927-bfb6b6de18ec">

2023-11-07 09:34 UTC, donalnofrixion requested changes
If I create a payout with a future scheduled date the edit dialog doesn't reflect this.

![Screenshot 2023-11-07 at 09 32 14](https://github.com/nofrixion/nofrixion.business/assets/89344328/953af76d-47bf-4908-b781-aa2e03f6773c)

2023-11-07 09:49 UTC, donalnofrixion commented
When on the Edit panel it feels weird that the escape takes you back to the Details panel. Personally I think it should replace the details modal.

2023-11-07 09:56 UTC, donalnofrixion commented
Should the 'No changes made button' be visible when first entering the edit modal? I only see the 'Save changes' even if no changes were made.

2023-11-07 10:15 UTC, pabloi-nf requested changes
If I press enter when the edit panel shows up it's the same as pressing escape. 
I think the problem is that the back button is the first element to have focus. We should have the amount input as the first element in the tab index order.
<img width="449" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/dfedf435-ce59-4eea-af54-d49ead5f4ec1">

2023-11-08 13:17 UTC, donalnofrixion commented
> > When on the Edit panel it feels weird that the escape takes you back to the Details panel. Personally I think it should replace the details modal.
> 
> @donalnofrixion It makes sense what you say if we assume the user just wants to cancel the whole flow. In that case it's good to speed up the process. However, we don't know really the user intention here. Maybe they pressed the button by mistake and wanted to go back to the details, or they realized the change wasn't necessary and just wanted to proceed to authorise it. In most cases the user expectation is to go back to the previous state, which in this case is with the payout details panel open.

@pabloi-nf That's fair enough. Makes sense

2023-11-09 09:28 UTC, donalnofrixion requested changes
If I login with a user that has the role User I can't edit a payout. The save changes button isn't available

2023-11-09 09:28 UTC, donalnofrixion commented on packages/components/src/components/ui/organisms/SavePayoutModal/SavePayoutModal.tsx
> +                        <span>{selectedPayout ? 'Save changes' : 'Create and authorise'}</span>
Should this be on the save button below instead? If the user isn't an Approver this button won't be available.

2023-11-09 09:39 UTC, donalnofrixion commented on packages/components/src/components/functional/SavePayoutModal/SavePayoutModal.tsx
> +        onSavePayout={selectedPayout ? onUpdatePayout : onCreatePayout}
I think this should be split into 2 events. onCreatePayout and onSavePayout. The logic isn't very explicit here and might lead to a misunderstanding

2023-11-09 13:34 UTC, pabloi-nf requested changes
If I try to remove a description it allows me to save changes, but the changes are not saved.
See video

https://github.com/nofrixion/nofrixion.business/assets/127946572/ee689241-0a12-44d2-b846-6eeb8a3a0df7

2023-11-09 13:41 UTC, donalnofrixion commented
@pabloi-nf Just a thought. When editing a payout I think it would be good to be able to approve it at the same time. Similar to creating a payout?

2023-11-09 13:56 UTC, pabloi-nf commented
@agranillonf something weird happens here. If I make a change on the edit screen, but then move to another tab or window, the changes dissappear and the data goes back to its original state.

https://github.com/nofrixion/nofrixion.business/assets/127946572/f3955914-d2be-46cc-9c40-bba4ee459a8b

2023-11-09 14:00 UTC, pabloi-nf requested changes
The style of the disabled button has to be:
text- color: #73808C
bg-color: #E3E5E8

2023-11-09 14:05 UTC, pabloi-nf commented
> @pabloi-nf Just a thought. When editing a payout I think it would be good to be able to approve it at the same time. Similar to creating a payout?

that makes sense @donalnofrixion. My only thought is if a user would expect to be able to authorise it right here, but if it clearly label the buttons that's probably nor a big concern.

We can change the button text from "create" to "save":

<img width="652" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/38c5adca-e65f-4ca6-a8d0-a2033fcac6b3">

2023-11-09 14:10 UTC, donalnofrixion commented
> > @pabloi-nf Just a thought. When editing a payout I think it would be good to be able to approve it at the same time. Similar to creating a payout?
> 
> that makes sense @donalnofrixion. My only thought is if a user would expect to be able to authorise it right here, but if we clearly label the buttons that's probably not a big concern.
> 
> We can change the button text from "create" to "save":
> 
> <img alt="image" width="652" src="https://user-images.githubusercontent.com/127946572/281756637-38c5adca-e65f-4ca6-a8d0-a2033fcac6b3.png">

When I edited a payout it was the first thing I expected to be able to do.

2023-11-10 01:27 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/128.

2023-11-10 02:05 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/128.

2023-11-10 09:13 UTC, donalnofrixion approved these changes

2023-11-10 09:44 UTC, pabloi-nf requested changes
The problem where fields are not deleted still happens.

https://github.com/nofrixion/nofrixion.business/assets/127946572/05f17df2-3c3f-449f-b22b-a8e1c0557d90

2023-11-10 16:36 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/128.

2023-11-10 16:39 UTC, donalnofrixion approved these changes

2023-11-10 16:44 UTC, pabloi-nf approved these changes

2023-11-10 16:46 UTC, Publicker commented
![crab rave](https://github.com/nofrixion/nofrixion.business/assets/52673485/5040a6c5-0eff-4497-9144-cd714e8aa18a)

2023-11-10 20:05 UTC, merged