Fix icon transition animations in Tag component
nofrixion/nofrixion.business pull request #137
Opened 2023-11-10 17:46 UTC by Publicker

Fixes an issue where clicking the "X" icon to delete a Tag resulted in a strange horizontal transition effect for both the "X" and tick icons. This effect has now been resolved.

Demo videos before and after the fix have been attached.

# Before
https://github.com/nofrixion/nofrixion.business/assets/52673485/51db43ee-0a01-4f2c-b659-d58f1b490856

# After
https://github.com/nofrixion/nofrixion.business/assets/52673485/dbcf45e3-2b98-4023-8384-2a9a00c85813

2023-11-10 17:51 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/137.

2023-11-10 18:41 UTC, sipsorcery approved these changes

2023-11-11 09:46 UTC, donalnofrixion approved these changes

2023-11-13 10:20 UTC, pabloi-nf requested changes
There is still an odd animation when the icons move out.
The X seems to move up or down depending where it went after the transition. Ideally there should be no movement for the icons, only opacity transition for the IN animation. OUT animations should be instant. This should be a rule of thumb for almost all default transitions

https://github.com/nofrixion/nofrixion.business/assets/127946572/fd3bb7d1-ce41-4bec-9d0e-21aa6b1c41dd

2023-11-13 15:45 UTC, pabloi-nf approved these changes

2023-11-13 16:06 UTC, merged