Feature/moov 2064 accounts list component
nofrixion/nofrixion.business pull request #15
Opened 2023-08-14 16:37 UTC by arifmatin

- Current Accounts Header component
- Current Accounts List component (UI and functional) actions not implemented yet.
- Accounts component
- Atom: DispayAndCopy (account indicators) component
- Account Amount (will do in a separate task)

![currentaccountlist](https://github.com/nofrixion/nofrixion.business/assets/92720032/76139410-1008-496d-ace8-40293feed335)

2023-08-14 17:22 UTC, donalnofrixion commented
Looks great Arif! Just a few small comments.

2023-08-14 17:22 UTC, donalnofrixion requested changes

2023-08-14 17:22 UTC, donalnofrixion commented on packages/components/src/components/ui/Account/Account.tsx
> +const Account: React.FC<AccountProps> = ({ account, onAccountClick }) => {
I think AccountCard instead for the component name?

2023-08-14 17:22 UTC, donalnofrixion commented on packages/components/src/components/ui/Account/Account.tsx
> +          <span>
Anything displaying an amount needs the class 'tabular-nums'

2023-08-15 08:39 UTC, arifmatin commented on packages/components/src/components/ui/Account/Account.tsx
> +const Account: React.FC<AccountProps> = ({ account, onAccountClick }) => {
Yeah sure

2023-08-15 09:01 UTC, Publicker requested changes
Great progress so far @arifmatin! Just leaving some minor comments, if you have any questions, please don't hesitate to ask me.

2023-08-15 09:01 UTC, Publicker commented on packages/components/src/utils/uiFormaters.tsx
> +const formatCurrency = (currency: Currency) => {
If you see that this could be used anywhere apart from where you just used it, please do! I think it's a pretty good formatter and should've been done before🤘🏻

2023-08-15 11:25 UTC, pabloi-nf requested changes
- Button should not stretch:
<img width="1249" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/97d11e82-10eb-4c89-a4fd-dc99e0d732e9">
<br><br><br>

- Icon should be 12x12px, and the button should have the hover state.
<img width="69" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/06be937f-225f-451d-aade-5f86ffab814d">
<img width="69" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/add3ad88-f67b-4595-94d4-034198d40fa7">
<br><br><br>
- Numbers should have the font-feature-settings: "cv01","cv02","cv03","cv04"
<img width="299" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/74b372de-9b5b-48d5-9360-e2e6ab9dfb8e">
<br><br><br>

- Name and IBAN should be vertically centered. They should have 2.5 rem margin top and bottom. 

<img width="319" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/4787686e-75ad-401e-92ec-f64428feaf9a">
<img width="1064" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/ca55b637-f3a0-490d-9e69-703a2317c3ae">

- The Account boxes should have rounded corners and a drop shadow like the when the mouse is on hover. Check Figma file for reference.
https://www.figma.com/file/Sc96Upmn3MpOmvM9jgvaUG/MMB-Portal-%2F-HiFi?type=design&node-id=5224%3A33863&mode=design&t=ERVhr7aqyP5AQsFs-1

2023-08-16 14:19 UTC, donalnofrixion approved these changes

2023-08-16 14:21 UTC, Publicker approved these changes
Very nice! 🔥

2023-08-16 14:43 UTC, merged