Feature/moov 2260 system error messages
nofrixion/nofrixion.business pull request #152
Opened 2023-11-30 16:58 UTC by arifmatin

- System error modal 
-Only wired-up for connected accounts 

If this is ok, I'll do the other pages in a separate PR

https://github.com/nofrixion/nofrixion.business/assets/92720032/2400743a-4bf8-4527-95f3-416fa4f2e256

2023-11-30 17:03 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/152.

2023-11-30 22:21 UTC, agranillonf approved these changes

2023-12-01 06:55 UTC, donalnofrixion requested changes

2023-12-01 06:55 UTC, donalnofrixion commented on packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
> +        setSystemErrorTitle(`Renew connected account has failed`)
I'd create a function to call for these 3 lines.

2023-12-01 09:42 UTC, arifmatin commented on packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
> +        setSystemErrorTitle(`Renew connected account has failed`)
Yeah sure

2023-12-01 10:52 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/152.

2023-12-01 11:43 UTC, Publicker commented on packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
> +  const [systemErrorMessage, setSystemErrorMessage] = useState<string | undefined>(undefined)
Just a small suggestion - how about combining these two into a single state with an interface specifically for system errors? It would then be something like this:

So it would look like this instead:
```suggestion
  const [systemError, setSystemError] = useState<SystemError | undefined>(undefined)
```

2023-12-01 11:43 UTC, Publicker commented on packages/components/src/components/ui/atoms/Icon/Icon.tsx
> +  'error/48': (className: string) => (
We typically match the icon names to what's shown in Figma. For this one, it's labeled 'Alert' instead of 'error':

![Screenshot 2023-12-01 at 08 41 06](https://github.com/nofrixion/nofrixion.business/assets/52673485/050a1453-ab87-4f56-ac0b-2a69fcc12647)

2023-12-01 11:48 UTC, arifmatin commented on packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
> +  const [systemErrorMessage, setSystemErrorMessage] = useState<string | undefined>(undefined)
Ah yes. Will do that

2023-12-01 11:49 UTC, arifmatin commented on packages/components/src/components/ui/atoms/Icon/Icon.tsx
> +  'error/48': (className: string) => (
Must of missed that. Will change the name

2023-12-01 11:49 UTC, Publicker commented on packages/components/src/components/functional/CurrentAccountsList/CurrentAccountsList.tsx
> +  const [systemErrorMessage, setSystemErrorMessage] = useState<string | undefined>(undefined)
Thanks!

2023-12-01 11:49 UTC, Publicker commented on packages/components/src/components/ui/atoms/Icon/Icon.tsx
> +  'error/48': (className: string) => (
🤘🏻🤘🏻🤘🏻

2023-12-01 11:54 UTC, pabloi-nf requested changes
Thanks @arifmatin, it looks good.

A few comments:

The line height for the big title should be 2rem. It's currently in 1.5rem.
This should apply for all pop up boxes, not just the errors.

Another thing I noticed is that the width of the box is smaller than in the figma.
It's currently 28rem but it should be 33rem. This should also apply to the bank connection box and as a default minimum for pop up boxes in desktop.


<img width="615" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/6207ced0-c38d-4eb1-97b0-13fc927adb27">

Thanks

2023-12-01 14:42 UTC, Publicker approved these changes

2023-12-01 15:53 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/152.

2023-12-04 15:12 UTC, merged