Separated void and refund with the likes of checkout
nofrixion/nofrixion.business pull request #17
Opened 2023-08-15 11:11 UTC by sauravmaiti22

The way checkout handles void and refund is -
1. If no amount has been captured and amount has been authorised, then they show a Void payment option.
2. If some or full of the authorisation is captured, then they show a refund option and no Void option is provided.
3. This way the user can perform only one operation at a time. A captured or partially captured payment cannot be voided.

This PR implements the same behaviour in MM4B.

2023-08-15 11:12 UTC, sauravmaiti22 commented
> The way checkout handles void and refund is -
> 
> 1. If no amount has been captured and amount has been authorised, then they show a Void payment option.
> 2. If some or full of the authorisation is captured, then they show a refund option and no Void option is provided.
> 3. This way the user can perform only one operation at a time. A captured or partially captured payment cannot be voided.
> 
> This PR implements the same behaviour in MM4B.


https://github.com/nofrixion/nofrixion.business/assets/103389834/fe14940f-b36e-41b3-8087-7371c596dffe

2023-08-15 12:55 UTC, donalnofrixion requested changes

2023-08-15 13:01 UTC, sauravmaiti22 commented on packages/components/src/components/ui/PaymentAttemptActionMenu/PaymentAttemptActionMenu.tsx
> +            {!isCardVoid && (
@donalnofrixion Earlier I was going to the modal directly on the click of context menu as there was just one option. But that was not the design. Now context menu will always show even when there is just one option. Maybe @pabloi-nf can clarify.

2023-08-15 13:05 UTC, donalnofrixion commented on packages/components/src/components/ui/PaymentAttemptActionMenu/PaymentAttemptActionMenu.tsx
> +            {!isCardVoid && (
Personally, I think it looks wrong. And hidden. I think a regular user will have a hard time finding it. A button for either void or refund might be a better option. There seems to be enough room for it

2023-08-15 13:11 UTC, pabloi-nf commented on packages/components/src/components/ui/PaymentAttemptActionMenu/PaymentAttemptActionMenu.tsx
> +            {!isCardVoid && (
We considered that option before, but went with this one to be safe with the screen sizes and expecting that other options could be added later.

If you both think it's an option, we can keep the current behaviour for mobile and expose the button for desktop, like we have on 'capture'.

2023-08-15 13:13 UTC, sauravmaiti22 commented on packages/components/src/components/ui/PaymentAttemptActionMenu/PaymentAttemptActionMenu.tsx
> +            {!isCardVoid && (
@donalnofrixion There was a discussion about this previously and the reason why it's not a button is because it's a rare  action and we don't want unnecessary attention on it. Earlier we had show on hover thing which Aaron did not like as it was hidden and difficult to find. So Pablo came up with this.

2023-08-15 13:23 UTC, pabloi-nf commented on packages/components/src/components/ui/PaymentAttemptActionMenu/PaymentAttemptActionMenu.tsx
> +            {!isCardVoid && (
What Saurav mentions was also discussed. I think now that maybe, even being considered a rare action, it can be a good thing to show merchants that MMB is a platform that allows these kinds of operations. With that in mind, showing the button can be a good idea

2023-08-15 14:19 UTC, pabloi-nf commented on packages/components/src/components/ui/PaymentAttemptActionMenu/PaymentAttemptActionMenu.tsx
> +            {!isCardVoid && (
We can do it like this 
<img width="733" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/cf8a5902-55fb-4dab-8fed-9a172a0a5bca">

2023-08-15 15:17 UTC, sauravmaiti22 commented on packages/components/src/components/ui/PaymentAttemptActionMenu/PaymentAttemptActionMenu.tsx
> +            {!isCardVoid && (
Okay let me add these buttons.

2023-08-15 15:50 UTC, donalnofrixion requested changes

2023-08-15 15:50 UTC, donalnofrixion commented on packages/components/src/components/ui/CardRefundModal/CardRefundModal.tsx
>                <button
There's a Button component you can use for this. Also can you update other buttons in the modal?

2023-08-15 16:22 UTC, sauravmaiti22 commented on packages/components/src/components/ui/CardRefundModal/CardRefundModal.tsx
>                <button
Oh let me check

2023-08-15 16:54 UTC, sauravmaiti22 commented on packages/components/src/components/ui/CardRefundModal/CardRefundModal.tsx
>                <button
Switched the buttons to use Button atom.

2023-08-16 07:06 UTC, donalnofrixion approved these changes

2023-08-16 09:32 UTC, pabloi-nf approved these changes

2023-08-16 09:33 UTC, merged