Edit columns component and functionality
nofrixion/nofrixion.business pull request #178
Opened 2024-01-15 13:41 UTC by sauravmaiti22

- Added a new component called EditColumns which is a headless UI popover primitive.
- This component accepts a list of columns that have an id and label. The id is useful for instances in future if we decide to rename a column, the id wouldn't change and the persisted selection will be valid.
- If the user tries to deselect all columns, then the last selected column checkbox will be disabled.
- The column selector is placed at the bottom of table as per new design which will have paging next to it - https://www.figma.com/file/Sc96Upmn3MpOmvM9jgvaUG/MMB-Portal-%2F-HiFi?type=design&node-id=11056%3A53890&mode=design&t=f3Wfhuu5ek6yxVKd-1. Will be implemented in a separate task.
- Have to add new columns to the table that will be deselected by default. Also have to implement horizontal scroll. Will be done in separate task. 
- Had to refactor the pr table to combine tags and context menu in a single <td> to let the last column take up all the remaining  space.
- Added conditional rendering of columns based on selection.
- Added a store to save selection of columns in local storage.

2024-01-15 13:47 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/178.

2024-01-15 14:08 UTC, donalnofrixion approved these changes

2024-01-15 14:08 UTC, donalnofrixion commented on packages/components/src/components/ui/atoms/DropDown/DropDown.tsx
> -  //   DropdownMenuCheckboxItem,
Can these be removed?

2024-01-15 14:08 UTC, donalnofrixion commented
Very nice! 🔥

2024-01-15 14:09 UTC, sauravmaiti22 commented on packages/components/src/components/ui/atoms/DropDown/DropDown.tsx
> -  //   DropdownMenuCheckboxItem,
Oh yes. Let me remove it.

2024-01-15 14:15 UTC, laucait approved these changes

2024-01-16 09:49 UTC, pabloi-nf requested changes
Looking good!

The only thing to adjust is the margins. I can see it has too much at the bottom.
<img width="147" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/6c2fe23a-4fc9-4655-bb5d-af2fc3ea0934">

I was making a guide for general pages and components in Figma that we can use as reference for this.
https://www.figma.com/file/Sc96Upmn3MpOmvM9jgvaUG/MMB-Portal-%2F-HiFi?type=design&node-id=11589%3A60410&mode=dev

Another thing is that it needs a distance between the icon and the opened panel. We should give 1rem distance to the edge of the icon.
<img width="171" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/f1b458ba-4a6d-490f-b5ed-c4f270d37064">

2024-01-16 10:08 UTC, arifmatin approved these changes

2024-01-16 10:40 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/178.

2024-01-17 09:33 UTC, pabloi-nf approved these changes

2024-01-17 09:50 UTC, merged