Feature/moov 2615 support lightning attempts
nofrixion/nofrixion.business pull request #182
Opened 2024-01-19 16:59 UTC by arifmatin

![image](https://github.com/nofrixion/nofrixion.business/assets/92720032/e7f4e384-8bae-4c72-9e26-a14b95cebaf0)

![image](https://github.com/nofrixion/nofrixion.business/assets/92720032/987fe6ca-ec41-4484-856e-45d726276fb9)

2024-01-19 17:05 UTC, Publicker commented on packages/components/src/components/ui/atoms/Icon/Icon.tsx
> +    </SVG>
If possible, can we remove the strokes colors/linecap/linejoin from the SVG itself and set the color from where it's used?

2024-01-19 17:07 UTC, arifmatin commented on packages/components/src/components/ui/atoms/Icon/Icon.tsx
> +    </SVG>
Ah yes will do

2024-01-19 17:30 UTC, pabloi-nf requested changes
- The icon is getting a stroke around the green circle that shouldn't be there 
<img width="54" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/14c175a1-7743-4ce2-ba99-72b853d2c829">
- When I read "1 Bitcoin payment received" it seemd I was receiving 1 BTC as a payment. Would it be correct and less misleading to say "1 Lightning payment received"?

2024-01-19 17:48 UTC, agranillonf approved these changes
Same question as Pablo I. regarding the "Bitcoin payment" labeling.

2024-01-22 11:02 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/182.

2024-01-22 12:00 UTC, arifmatin commented
![image](https://github.com/nofrixion/nofrixion.business/assets/92720032/1a054a5a-7322-4fe2-aa96-959c9f69de3a)

![image](https://github.com/nofrixion/nofrixion.business/assets/92720032/b0b11d57-108d-4c1b-971c-912baa6545e8)

2024-01-22 12:03 UTC, pabloi-nf approved these changes

2024-01-22 14:08 UTC, Publicker commented on packages/components/src/utils/parsers.ts
> +
I was just looking at this and noticed a few too many `ifs` - would you mind moving this to a `switch` structure?

2024-01-22 15:35 UTC, arifmatin commented on packages/components/src/utils/parsers.ts
> +
Don't know if can use switch here as we're looking for payment attempt fields here.

2024-01-22 16:28 UTC, Publicker commented on packages/components/src/utils/parsers.ts
> +
You're right! Sorry about that.

2024-01-22 16:28 UTC, Publicker approved these changes

2024-01-22 16:29 UTC, merged