Introduce New Payrun Details Page with Editable Invoice Features
nofrixion/nofrixion.business pull request #188
Opened 2024-01-24 16:20 UTC by Publicker

This PR marks the introduction of a new 'Payrun Details' page in MM4B. This page allows users to review and modify payrun details before execution.

# Changes
- **New Payrun Details Page**: Developed a new page for handling the details of payruns. This includes functionality to modify individual invoice amounts and remove invoices as needed before completing the payrun.
- **Functional Component 'PayrunDetails'**: Created a new functional component along with its full UI. This component supports all local UI validations required for the Payrun Details page.
- **Updated Accounts Payable Page**: Enhanced the "Payrun" tab in the Accounts Payable page to display minimal information about created payruns. Users can now click on a payrun to navigate to the detailed Payrun Details page.

# Big Notes/Caveats
- **Temporary Local Data Changes**: Currently, modifications in the Payrun Details are only local and not persisted. The data gets reset upon leaving the page. Integration with the backend for permanent changes is planned as a subsequent update.
- **Minimal Payrun Listing**: The listing of payruns is basic and primarily serves as a means to access the Payrun Details page. It is not the focus of this task and should not be scrutinized for testing rigor at this stage.

# Resources
### Demo video

https://github.com/nofrixion/nofrixion.business/assets/52673485/792ce63f-72ad-4082-a729-bd0e67f6c68f

### CSV
New CSV file for testing grouped invoices:  [invoices-working-3-beneficiaries.csv](https://github.com/nofrixion/nofrixion.business/files/14041021/invoices-working-3-beneficiaries.csv)

2024-01-24 16:27 UTC, sauravmaiti22 commented on packages/clients/src/hooks/usePayrun.ts
> +    enabled: !!payrunId,
Would it be useful to have placeholder data here by fetching it from Payruns query? It will not take time to load if we have that.

2024-01-24 16:29 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/188.

2024-01-24 16:33 UTC, sauravmaiti22 commented
Looks awesome!

2024-01-24 16:34 UTC, donalnofrixion approved these changes

2024-01-24 16:34 UTC, donalnofrixion commented
🔥

2024-01-24 16:44 UTC, arifmatin approved these changes

2024-01-24 16:48 UTC, Publicker commented on packages/clients/src/hooks/usePayrun.ts
> +    enabled: !!payrunId,
Good catch! Just committed this, thanks @sauravmaiti22!

2024-01-24 16:55 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/188.

2024-01-25 11:00 UTC, pabloi-nf requested changes
Good work!
A few comments:

- When I'm in a payrun detail page, clicking the "All payruns" link should bring me back to the payruns tab, but is sending me to the payouts page instead.
- The default name of payruns should take the year and a number. For example "2024-1", if it's the first payrun of the year, and so on. The user can modify the name.
- The number 1 style on the account balance field should have the normal style, not the style with the bottom base line. 

> <img width="141" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/adca384e-07db-4bdf-889c-55f03d464abd">

- If there is only one payout, there shouldn't be a bottom separator line:

> <img width="286" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/211b11ca-6cc5-4d98-875c-3f4356ab1184">

- The separator lines color seems too light. It should be #F1F2F3.

- If the user switches off the payout (but not the invoice inside), the amount should remain the same. It's incorrect to say that the payout is 0 and it has no invoices included. The only amount that changes to 0 is the total amount to pay, and it's correct to say there are no payouts included. 
> <img width="280" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/d0b7bb36-f13a-4554-8027-1e961ddfd138">

- We should use ellipsis for long account names:
> <img width="314" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/4502321a-bc3e-43ee-9792-174cd1e5373c">
- The margins of the payout rows shuld be only 1 rem. It has 2 rems now because it adds to different paddings:
> <img width="123" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/e22c8e1c-8cdf-4a65-9ba0-3b25651493e8">

- This warning shouldn't appear as the first thing visible
> <img width="497" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/e87bde2c-adf9-4fab-a999-9cd4f4dcfd25">

- Let's reduce this margin bottom to be 3rem instead of 5.5.
> <img width="127" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/95ecaf67-3d6e-4b4f-9ba3-d0cdf25d36ae">

- I standardized in Figma for left and right margins for pages and elements. We can use that for this and all pages. https://www.figma.com/file/Sc96Upmn3MpOmvM9jgvaUG/MMB-Portal-%2F-HiFi?type=design&node-id=11549%3A57306&mode=dev&t=QzqqSpv7KRLsgl0X-1
> ![image](https://github.com/nofrixion/nofrixion.business/assets/127946572/ea7aa857-6768-45e4-83e8-c3ab6eb75491)

- The column titles need to be right aligned with the amounts
> <img width="395" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/1be7f667-c51d-42a1-bd74-e3e5894aaf6d">

- The numbers in this columns need to be tabular numbers
> <img width="145" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/e7889583-67ae-4c65-b16a-44868935c824">

- Adapt text to reflect how many invoices are included in a payout
> ![image](https://github.com/nofrixion/nofrixion.business/assets/127946572/4e9d28fa-a322-4cc2-86f2-f2163b4fa0b0)

2024-01-26 11:19 UTC, agranillonf approved these changes

2024-01-30 16:40 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/188.

2024-01-30 16:42 UTC, Publicker commented
@pabloi-nf I've made all the changes except for standardising the padding/margins across pages. That would be a separate task and involves more work beyond what's related to Payrun.

2024-01-31 09:41 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/188.

2024-01-31 11:45 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/188.

2024-01-31 13:35 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/188.

2024-01-31 13:39 UTC, pabloi-nf approved these changes

2024-01-31 13:45 UTC, merged