New paging mechanism
nofrixion/nofrixion.business pull request #189
Opened 2024-01-26 11:36 UTC by sauravmaiti22

- Added a new paging mechanism where the user can select a different page size through dropdown.
- Have kept 4 page sizes to select from 10, 20, 50, 100.
- The default page size for all tables is 20.
- The selected sizes are stored in local storage.
- Added got to first and last page icons and functionality to pager.

2024-01-26 11:42 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/189.

2024-01-26 11:45 UTC, sauravmaiti22 commented
Just realised, for payment request dashboard, I need to use default page size in mobile. Will make that change.

2024-01-26 15:17 UTC, pabloi-nf requested changes
Good work Saurav!
A few comments:

- Numbers should be right aligned.
> <img width="131" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/7a7e71d2-29fb-4d5f-8479-0851459f124f">

- We are missing the text "per page"
> ![image](https://github.com/nofrixion/nofrixion.business/assets/127946572/ab7f589a-4fd6-4603-9307-c6ed68af7068)

- It needs to have 1rem between the number and the icon 
> <img width="62" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/52728bd5-e4b4-4d00-a680-3848e27e36af">

- It's very difficult to see the color change in hover. I recorded a video and it seems it's not changing.

> https://github.com/nofrixion/nofrixion.business/assets/127946572/53010f30-c499-4952-bfb3-30f7b7d0bdd6

- There is s weird behaviour when changing page. The screen jumps to the middle of the list.

https://github.com/nofrixion/nofrixion.business/assets/127946572/a925115a-11ec-4a1a-b085-748cab41126e

2024-01-26 15:36 UTC, donalnofrixion requested changes

2024-01-26 15:36 UTC, donalnofrixion commented on packages/components/src/components/functional/AccountDashboard/AccountDashboard.tsx
> +  const { pageSizes, setPageSizes } = useStore(usePageSizesStore, (state) => state) ?? {
I think it might be worth creating a reusable hook for this

2024-01-26 17:11 UTC, sauravmaiti22 commented
> Good work Saurav! A few comments:
> 
> * Numbers should be right aligned.
> 
> > <img alt="image" width="131" src="https://private-user-images.githubusercontent.com/127946572/300024525-7a7e71d2-29fb-4d5f-8479-0851459f124f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODI2NzcsIm5iZiI6MTcwNjI4MjM3NywicGF0aCI6Ii8xMjc5NDY1NzIvMzAwMDI0NTI1LTdhN2U3MWQyLTI5ZmItNGQ1Zi04NDc5LTA4NTE0NTlmMTI0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNTE5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzkxN2U1ZjdiYWIwY2FhNDA1YmQwZWEzN2NmNzAwZTBmYjBhNWQ2MTQzMTM3NGQ4ZTBhZDdmMzc3ZGFmMTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.243YOiYE6ELSCccvKdoXyylUw3aZr74M0FHKFXNYqyg">
> 
> * We are missing the text "per page"
> 
> > ![image](https://private-user-images.githubusercontent.com/127946572/300024844-ab7f589a-4fd6-4603-9307-c6ed68af7068.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODI2NzcsIm5iZiI6MTcwNjI4MjM3NywicGF0aCI6Ii8xMjc5NDY1NzIvMzAwMDI0ODQ0LWFiN2Y1ODlhLTRmZDYtNDYwMy05MzA3LWM2ZWQ2OGFmNzA2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNTE5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDgyNDhjY2Y2OGQxYmMyZTUyNTRiMjIzMGU2MzQ2YTRmYjU1ZTMzMzZkYTdiNjBhMzQzNjhmYTFhNjgzN2E1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DDtJDqMEMSt7zKQVjyUN-jomIASfBPILE_QuodO_n4o)
> 
> * It needs to have 1rem between the number and the icon
> 
> > <img alt="image" width="62" src="https://private-user-images.githubusercontent.com/127946572/300025159-52728bd5-e4b4-4d00-a680-3848e27e36af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODI2NzcsIm5iZiI6MTcwNjI4MjM3NywicGF0aCI6Ii8xMjc5NDY1NzIvMzAwMDI1MTU5LTUyNzI4YmQ1LWU0YjQtNGQwMC1hNjgwLTM4NDhlMjdlMzZhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQxNTE5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2U4YWVjNDcwZmUyMjliNDAzN2I0MzZjZWNlZDU0YjYxMjZhNjJiYmY0ODk3YWY4NTEwNzRlZmU3MjhlYTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zRYokUP0D1tgKCkcPHYonpWRTztzxf-WbXJ-r9kZLZg">
> 
> * It's very difficult to see the color change in hover. I recorded a video and it seems it's not changing.
> 
> > Screen.Recording.2024-01-26.at.15.14.09.mov
> 
> * There is s weird behaviour when changing page. The screen jumps to the middle of the list.
> 
>  Screen.Recording.2024-01-26.at.15.15.36.mov

Thanks @pabloi-nf! Fixed all the issues.

2024-01-26 17:11 UTC, sauravmaiti22 commented on packages/components/src/components/functional/AccountDashboard/AccountDashboard.tsx
> +  const { pageSizes, setPageSizes } = useStore(usePageSizesStore, (state) => state) ?? {
Great idea! Created a hook that makes it very simple to use.

2024-01-26 17:15 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/189.

2024-01-27 07:54 UTC, donalnofrixion approved these changes

2024-01-29 09:56 UTC, arifmatin approved these changes

2024-01-29 11:59 UTC, Publicker approved these changes

2024-01-29 11:59 UTC, Publicker commented on packages/components/src/components/ui/molecules/PageSizesDropdown/PageSizesDropdown.tsx
> +        <div className="cursor-pointer flex flex-row items-center gap-5 p-2 rounded border-solid border-[1px] border-[#D5DBDD]">
You'd use `border-border-grey` here

2024-01-29 12:07 UTC, sauravmaiti22 commented on packages/components/src/components/ui/molecules/PageSizesDropdown/PageSizesDropdown.tsx
> +        <div className="cursor-pointer flex flex-row items-center gap-5 p-2 rounded border-solid border-[1px] border-[#D5DBDD]">
Thanks @Publicker. Made the change.

2024-01-29 12:13 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/189.

2024-01-29 13:46 UTC, pabloi-nf requested changes
Thanks Saurav.

Everything looks fine, but there are 2 details:

- The font size of the "per page" text is too big. It should be 13px (0.8125rem)
> <img width="167" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/43e15686-c52b-4564-9c97-6259454a5975">

- The page doesn't jump when I move forward on the pages, but it still jumps when I go to a previous page.

https://github.com/nofrixion/nofrixion.business/assets/127946572/a6c3f4b7-4a92-46b4-8591-ccced198e892

2024-01-29 15:31 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/189.

2024-01-29 15:44 UTC, sauravmaiti22 commented
> Thanks Saurav.
> 
> Everything looks fine, but there are 2 details:
> 
> * The font size of the "per page" text is too big. It should be 13px (0.8125rem)
> 
> > <img alt="image" width="167" src="https://private-user-images.githubusercontent.com/127946572/300481744-43e15686-c52b-4564-9c97-6259454a5975.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1NDIzOTIsIm5iZiI6MTcwNjU0MjA5MiwicGF0aCI6Ii8xMjc5NDY1NzIvMzAwNDgxNzQ0LTQzZTE1Njg2LWM1MmItNDU2NC05Yzk3LTYyNTk0NTRhNTk3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxNTI4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjIyMWYzZDRkMzRkYjZlZTE2ZTQ4OTdlOGZhOWVmNDNhM2UyM2I2OTE1ZjZhMWNlYjQwNGE5MmU2Y2I2M2RhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lkl8dTjFLk8fosRj4dTKKQLZNgt-pUmP26JH4wce4Xc">
> 
> * The page doesn't jump when I move forward on the pages, but it still jumps when I go to a previous page.
> 
>  Screen.Recording.2024-01-29.at.14.45.51.mov

@pabloi-nf Should be good now.

2024-01-30 09:37 UTC, pabloi-nf approved these changes

2024-01-30 09:38 UTC, merged