[MOOV-2697]: Added payrun CSV template to download links
nofrixion/nofrixion.business pull request #191
Opened 2024-02-01 01:10 UTC by agranillonf

Added CSV template download functionality to the payrun template download links.

---
Updated 01/02/2024:
Also added additional CSV import validations and improved error details:

|Before|After|
|-----|-----|
|![image](https://github.com/nofrixion/nofrixion.business/assets/114026805/ea322713-8db9-40ca-8517-0140bb50096c)|![image](https://github.com/nofrixion/nofrixion.business/assets/114026805/41c4fa00-1c39-4954-82f3-973db83ee9ea)|

Tests were made with this file:
[temp-test-6.csv](https://github.com/nofrixion/nofrixion.business/files/14130986/temp-test-6.csv)

2024-02-01 01:15 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/191.

2024-02-01 08:25 UTC, donalnofrixion requested changes

2024-02-01 08:25 UTC, donalnofrixion commented on packages/components/src/components/ui/Modals/ImportInvoiceModal/ImportInvoiceModal.tsx
> +    'InvoiceNumber,PaymentTerms,InvoiceDate,DueDate,Contact,Currency,Subtotal,Discounts,Taxes,TotalAmount,InvoiceStatus,Reference,RemittanceEmail,DestinationIban,DestinationAccountNumber,DestinationS
We have a type `LocalInvoice` with these fields defined. I think it might be better to use that to generate the columns. That way they can remain in sync if anything changes.

2024-02-01 11:14 UTC, Publicker commented
@agranillonf @donalnofrixion @pabloi-nf  What do you all think about offering a more comprehensive CSV template, possibly including examples? This way, users could get a feel for how a realistic file might appear.

Personally, if I were receiving the template, I'd appreciate seeing the specific format used for each field.

2024-02-01 11:39 UTC, pabloi-nf commented
> @agranillonf @donalnofrixion @pabloi-nf What do you all think about offering a more comprehensive CSV template, possibly including examples? This way, users could get a feel for how a realistic file might appear.
> 
> Personally, if I were receiving the template, I'd appreciate seeing the specific format used for each field.

It's a good idea. You mean to include data under the columns, correct?

2024-02-01 13:58 UTC, donalnofrixion commented
> @pabloi-nf Yes, exactly that.

A single row would do with valid date formats, etc

2024-02-01 21:05 UTC, agranillonf commented
Changes were made as per the discussions with @Publicker and Andrés.

2024-02-01 21:07 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/191.

2024-02-02 13:30 UTC, pabloi-nf approved these changes

2024-02-02 15:40 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/191.

2024-02-02 15:41 UTC, agranillonf commented
@pabloi-nf @Publicker Latest discussed changes have been applied.

2024-02-02 15:54 UTC, Publicker approved these changes

2024-02-02 16:58 UTC, pabloi-nf requested changes
Thanks Axel.

Let's remove the text "Which format to use?" and change the link text to "Download the CSV template".

The distance under the text should be bigger
<img width="138" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/c513f347-d6b3-4d71-ad45-76904167acfa">

I also noticed that the error text below is too big. It should be 13px.

Use this as a reference for sizes and distances:
https://www.figma.com/file/Sc96Upmn3MpOmvM9jgvaUG/MMB-Portal-%2F-HiFi?type=design&node-id=12255%3A60578&mode=dev

2024-02-02 19:55 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/191.

2024-02-06 09:39 UTC, arifmatin approved these changes

2024-02-06 14:26 UTC, pabloi-nf requested changes
Looks good!
The only adjustment is that the padding-bottom of the main title and the "Remember..." text should be both 1.5rem.
<img width="90" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/2cfae168-2371-4487-b59d-b253e005f994">

2024-02-07 20:28 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/191.

2024-02-08 12:12 UTC, pabloi-nf requested changes
Thanks Axel.

I see that the "Remember..." text still has 0.75rem for padding-bottom
<img width="891" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/cf768bf2-918f-42a3-a7a6-e4b6aebed388">

2024-02-08 15:05 UTC, agranillonf commented
@pabloi-nf It does, but the items on the list below have 0.75rem of padding at the top and bottom, making the space between the "Remember..." and the list 1.5rem. Is that ok?

2024-02-08 15:22 UTC, pabloi-nf commented
> @pabloi-nf It does, but the items on the list below have 0.75rem of padding at the top and bottom, making the space between the "Remember..." and the list 1.5rem. Is that ok?

@agranillonf yes, but If you look at the figma link I shared it shows these sizes 
<img width="721" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/1d072578-b07f-48f0-9d01-7e897473e276">

My comment was to change the CSS property of both elements

2024-02-08 16:20 UTC, agranillonf commented
My bad. Thing is, for some reason, I can no longer see the spacing sizes on Figma.

2024-02-08 16:40 UTC, Publicker commented
> My bad. Thing is, for some reason, I can no longer see the spacing sizes on Figma.

@agranillonf It looks like you might still have Dev Mode enabled in Figma. Since we no longer have access to it, you'll need to disable it to return to the workflow of the pre-Dev Mode era, where you'll be able to see the spacing as we did before.

https://github.com/nofrixion/nofrixion.business/assets/52673485/ff686468-6a25-4dd7-b24a-ec8bc3c6b7c6

2024-02-13 15:28 UTC, pabloi-nf approved these changes

2024-02-13 15:58 UTC, merged