Implement Save and Discard Mechanism for Changes in Payrun
nofrixion/nofrixion.business pull request #192
Opened 2024-02-01 11:10 UTC by Publicker

This PR introduces a new feature in the Payrun "configuration" process, including control over changes made to the selected payment account per currency and the inclusion of invoices in a payrun.

# Changes
- **New Save and Discard Buttons**: When changes are made to the account selected for payment or to the status of invoices being included or excluded from the payrun, "Save" and "Discard" buttons now appear. These buttons allow users to either commit their changes or revert them to the last saved state.
- **Confirmation on Navigation**: If a user attempts to navigate away from the page by clicking on "All Payruns" while unsaved changes are present, a native popup will warn them that leaving the page will result in the loss of those changes. This provides an opportunity to cancel the navigation, save the changes, and then proceed as intended.

# Big Notes/Caveats
- **Local Saving of Changes**: Currently, the changes are only saved locally. This limitation is due to the pending API work required to persist these changes server-side. As a result, if the page is reloaded, any unsaved changes will be lost.
- **Temporary UI Design**: The design of the "Save" and "Discard" buttons is temporary and subject to change. The current UI was implemented to allow for the development and testing of functionality. When design is ready, it will be addressed.

# Demo Video
https://github.com/nofrixion/nofrixion.business/assets/52673485/0e515637-8ead-44af-87bb-10faf3be3b33

2024-02-01 11:15 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/192.

2024-02-01 11:39 UTC, sauravmaiti22 commented on packages/clients/src/types/ApiResponses.ts
> +  accountsToPay?: Record<Currency, string>
I believe this is the source accounts to pay from. accountsToPay sounds more like the recipient account. Perhaps, we can call it sourceAccounts or accountsToPayFrom?

2024-02-01 13:13 UTC, donalnofrixion requested changes

2024-02-01 13:13 UTC, donalnofrixion commented on packages/clients/src/types/ApiResponses.ts
> +  accountsToPay?: Record<Currency, string>
+1 for sourceAccounts

2024-02-01 16:25 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/192.

2024-02-01 16:28 UTC, donalnofrixion approved these changes

2024-02-01 16:47 UTC, sauravmaiti22 approved these changes

2024-02-02 16:45 UTC, pabloi-nf requested changes
Thanks Pablo.

- I think the buttons work well so far. If we encounter any issues in the future we can think of making special buttons.
- The button should say "Save changes".
- The width of the save button should adapt to the text length.
- If the user makes a change and then changes it again to go back to the last saved version, the save options should go away.


- Let's use this dialog:

> ![image](https://github.com/nofrixion/nofrixion.business/assets/127946572/018825fb-b11d-4b78-bdda-1c2eed711f11)

2024-02-06 10:07 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/192.

2024-02-06 10:09 UTC, Publicker commented
Thanks, @pabloi-nf. Comments have been addressed.

2024-02-06 11:22 UTC, pabloi-nf requested changes
Thanks!
The leave dialog needs to appear on any link that takes the user out of this screen.

2024-02-06 17:12 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/192.

2024-02-06 17:17 UTC, Publicker commented
Should behave like that now @pabloi-nf

2024-02-07 13:44 UTC, Publicker commented
![This part of my life … this little part … is called … Happiness gif](https://github.com/nofrixion/nofrixion.business/assets/52673485/ce13f273-ac0d-4e1f-8b4d-aec39922e9a6)

2024-02-07 13:44 UTC, merged