[MOOV-2705]: Fixed tab decorations overlapping with menus
nofrixion/nofrixion.business pull request #193
Opened 2024-02-02 20:33 UTC by agranillonf

On mobile, the green tab accents would overlap with any visible pop-over or drop-down element.

2024-02-02 20:40 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/193.

2024-02-06 09:40 UTC, arifmatin approved these changes

2024-02-06 10:17 UTC, Publicker approved these changes

2024-02-06 14:20 UTC, pabloi-nf requested changes
I'm not sure what was the issue solved here, but I'm seeing no icons
![IMG_8063](https://github.com/nofrixion/nofrixion.business/assets/127946572/2b1d37ba-a886-4ed1-9d02-a0d3d09a1bb5)

2024-02-07 09:35 UTC, sauravmaiti22 commented
> I'm not sure what was the issue solved here, but I'm seeing no icons ![IMG_8063](https://private-user-images.githubusercontent.com/127946572/302660403-2b1d37ba-a886-4ed1-9d02-a0d3d09a1bb5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTg4MDMsIm5iZiI6MTcwNzI5ODUwMywicGF0aCI6Ii8xMjc5NDY1NzIvMzAyNjYwNDAzLTJiMWQzN2JhLWE4ODYtNGVkMS05ZDAyLWEwZDNkMDlhMWJiNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwOTM1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjUxOWY4MGFmNGY0MTVmM2VkZTYzZGZlYTE1YzY1OTZhNjBmNDhiMDg3MjA5NGU3NzlmOTlkZTY5MjVjZDUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4DPPZBZxBsWjfezhi2nfYr1KvXOocD2ZBvT3MrPj_TM)

I icons broke in this PR https://github.com/nofrixion/nofrixion.business/pull/188

2024-02-07 09:57 UTC, Publicker commented
@pabloi-nf, @sauravmaiti22 is correct - please disregard this issue for the current PR since it was something I caused in PR #188.

I'll be creating a new PR soon to address this.

2024-02-07 17:30 UTC, merged