Feature/moov 2687 pre authorisation screen
nofrixion/nofrixion.business pull request #196
Opened 2024-02-08 15:29 UTC by Publicker

This PR introduces a new Pre-Authorisation screen for Payruns, focusing on the UI aspect to enhance the payrun process flow within the application. This screen provides users with detailed information on the Payrun and includes options to proceed with the authorisation process.

# Changes
- **New Pre-Authorisation Screen**: Implemented the UI for the Pre-Authorisation screen accessible through the "Send request" flow in the Payrun Details screen (this was done like this just for testing reasons, after we have the email mechanism where user will get this URL this will get removed).

# Important Notes
- **Non-Functional State Changes**: Any modifications made in the Payrun Details screen are currently not integrated to affect the Payrun data presented in the Pre-Authorisation screen. This functionality will be developed and integrated in future updates.
- **Selected Accounts Placeholder**: The selected accounts section will appear empty for now. This is in anticipation of future integration where changes from the Payrun Details will reflect in this screen.
- **Inactive Buttons**: The "Reject" and "Accept and continue" buttons are present for UI completeness but are non-functional pending backend integration.

# Demo Video

https://github.com/nofrixion/nofrixion.business/assets/52673485/6e2b8195-3593-47e3-8f2c-c2344509d910

2024-02-08 15:41 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/196.

2024-02-08 15:48 UTC, donalnofrixion requested changes

2024-02-08 15:48 UTC, donalnofrixion commented on apps/business/src/pages/authLayout.tsx
> +      authState?.logOut && authState.logOut()
I don't think we're doing this anymore. We display an error dialog instead

2024-02-08 15:48 UTC, donalnofrixion commented on apps/business/src/pages/authLayout.tsx
> +const AuthLayout: React.FC<AuthLayoutProps> = ({ children }) => {
Can it be called something else? `AuthLayout` makes me think it's to do with authorisation

2024-02-08 15:57 UTC, Publicker commented on apps/business/src/pages/authLayout.tsx
> +      authState?.logOut && authState.logOut()
Maybe `SessionAuthProvider`?

2024-02-08 15:58 UTC, Publicker commented on apps/business/src/pages/authLayout.tsx
> +const AuthLayout: React.FC<AuthLayoutProps> = ({ children }) => {
Maybe SessionAuthProvider?

2024-02-08 15:59 UTC, Publicker commented on apps/business/src/pages/authLayout.tsx
> +      authState?.logOut && authState.logOut()
Alright - I will get rid of it

2024-02-08 16:24 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/196.

2024-02-08 16:34 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/196.

2024-02-09 09:46 UTC, Publicker commented on apps/business/src/pages/authLayout.tsx
> +      authState?.logOut && authState.logOut()
Created ticket for this and also discussing with @pabloi-nf what to do in this case. Exploring the option of showing a modal

2024-02-09 10:21 UTC, donalnofrixion approved these changes

2024-02-09 15:20 UTC, pabloi-nf requested changes
Thanks Pablo, it looks very good.

A few comments:

- The color of the status chip should be different. This is because we are using it on top of gray background instead of white, so we need to make the colours more vibrant.
> <img width="226" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/da2189c0-68ff-486d-8b14-8ad996552b0f">
> <img width="226" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/c8c84175-d44b-4be5-9ddb-bb2a77aa9f03">

- The font size of the "Notes for authoriser" needs to be 13px.
- Let's change the font-weight of the lorem ipsum text to 400. This was a mistake on the Figma.
- Make sure to align the content in the same vertical line. 
> 
<img width="252" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/89328b9f-14a9-4496-81a5-174cf491cbc1">

The text on top is currently aligned to the box, not to the content inside the box. 

For rounded buttons, the margin should be just 1rem from the edge of the box
> <img width="177" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/9fb9209d-6f9f-4656-910b-ee13860bcb82">


This is the guide https://www.figma.com/file/Sc96Upmn3MpOmvM9jgvaUG/MMB-Portal-%2F-HiFi?type=design&node-id=11549%3A57306&mode=dev&t=SAT6zUEzpcsLfBbZ-1

2024-02-13 13:33 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/196.

2024-02-13 13:37 UTC, arifmatin approved these changes

2024-02-13 13:38 UTC, Publicker commented
Thanks @pabloi-nf, should be good now.

2024-02-13 14:55 UTC, pabloi-nf approved these changes

2024-02-13 14:59 UTC, merged