Display Pay Run Notes from API
nofrixion/nofrixion.business pull request #208
Opened 2024-02-21 12:46 UTC by Publicker

This PR incorporates the ability to show Pay run notes fetched from the API. Additionally, it hides the notes section when no notes are present.

# Changes
- **Display Pay Run Notes**: Implemented functionality to display notes for each Pay run, as retrieved from the API. This feature allows users to view any additional information or comments associated with a Pay run, directly within the UI.
- **Conditional Notes Visibility**: Added logic to conditionally hide the notes block if a Pay run does not contain any notes.

# Screenshots
| No notes | Notes |
|--------|--------|
| ![No notes](https://github.com/nofrixion/nofrixion.business/assets/52673485/e9012e01-bc13-4bf8-b7d2-c1fe04105747) | ![Notes](https://github.com/nofrixion/nofrixion.business/assets/52673485/21fd86a7-5293-4d4a-abaa-acca9ea08a6c) |

2024-02-21 12:50 UTC, donalnofrixion approved these changes

2024-02-21 12:51 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/208.

2024-02-21 14:19 UTC, pabloi-nf requested changes
The notes text should have font-weight: 400

2024-02-22 13:37 UTC, pabloi-nf approved these changes

2024-02-22 15:17 UTC, merged