Display Authoriser Details on Pay Run Authorise Page and Update Date Formatting
nofrixion/nofrixion.business pull request #209
Opened 2024-02-21 13:54 UTC by Publicker

This PR brings enhancements to the Pay Run Authorise Page by displaying the authoriser's details and the date of authorisation upon a Pay run's authorisation. Additionally, it standardises the date format across the application to the Cardinal format, following a discussion with @pabloi-nf.

# Changes
- **Authoriser Details Display**: Now, when a Pay run is authorised, the Authorise Page will display both the name of the authoriser and the date when the authorisation occurred.
- **Date Format Standardisation**: Changed all date displays within the application to use the Cardinal format (e.g., April 4) instead of the Ordinal format (e.g., 4th April).

# Screenshot
![Authoriser details](https://github.com/nofrixion/nofrixion.business/assets/52673485/4dc8af0e-2594-4cd0-b351-e9ad0b316e36)

2024-02-21 14:04 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/209.

2024-02-21 14:14 UTC, arifmatin approved these changes

2024-02-21 14:16 UTC, sipsorcery approved these changes

2024-02-21 15:00 UTC, donalnofrixion approved these changes

2024-02-22 14:10 UTC, pabloi-nf requested changes
Works perfect.
We should add it too in the edit view
<img width="1676" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/d5a91f2e-2482-4aed-9bff-4e990c82523d">

2024-02-22 15:04 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/209.

2024-02-22 15:09 UTC, pabloi-nf approved these changes

2024-02-22 15:17 UTC, merged