Direct link to payment request details
nofrixion/nofrixion.business pull request #212
Opened 2024-02-21 17:18 UTC by arifmatin

Added direct link to payment request details using the search filter 

Added a copy link to the payment request details panel. The of the link is up for debate, I left it as Direct link. Any suggestions is welcomed. 

https://github.com/nofrixion/nofrixion.business/assets/92720032/664b3ab5-824b-4832-bf32-938bf96fc4c0

2024-02-21 17:38 UTC, sipsorcery commented
Very nice, worked perfectly for me.

2024-02-21 17:39 UTC, Publicker requested changes

2024-02-21 17:39 UTC, Publicker commented on packages/components/src/components/functional/PaymentRequestDetailsModal/PaymentRequestDetailsModal.tsx
> +      isWebComponent={isWebComponent}
I believe we can introduce a new abstraction at this point. Rather than using `isWebComponent`, we could use something like `showCopyLinkButton` to make it more generic. It's fine to have them in the components higher up because it aligns with their abstraction level. However, down here, we could be more specific about what changes depending on whether it's a web component or not.

2024-02-21 17:40 UTC, Publicker commented
Very cool! Just a small comment

2024-02-21 20:18 UTC, donalnofrixion commented
🔥 Sweet!

2024-02-21 20:18 UTC, donalnofrixion approved these changes

2024-02-22 10:11 UTC, arifmatin commented on packages/components/src/components/functional/PaymentRequestDetailsModal/PaymentRequestDetailsModal.tsx
> +      isWebComponent={isWebComponent}
Yeah sure I'll rename it for the details panel components.

2024-02-22 11:22 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/212.

2024-02-22 11:59 UTC, merged