Bank refund functionality v1
nofrixion/nofrixion.business pull request #32
Opened 2023-08-18 16:08 UTC by sauravmaiti22

Implemented bank refund functionality for bank payment attempts. Following cases tested:
1. Single bank refund.
2. Partial bank refund.
3. Payout delete -> Refund cancelled
4. Payout create -> Refund pending approval
5. Payout approve -> Refunded

**To test this in dev use nofrixion bank to make payment using a different merchant. This way the amount will get settled. Difficult to test with other banks.**

Version 2 - Need to work on approval flow after changes in bff. Will create an item for that.

2023-08-18 16:29 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/32.

2023-08-18 18:22 UTC, donalnofrixion requested changes

2023-08-18 18:22 UTC, donalnofrixion commented on packages/components/src/components/ui/BankRefundModal/BankRefundModal.tsx
> +            <div className="bg-white max-h-screen overflow-auto">
Are all these divs needed? They seem to share css. Can they be merged into one div?

2023-08-18 18:22 UTC, donalnofrixion commented on packages/components/src/components/ui/molecules/Select/SelectAccount/SelectAccount.tsx
> +              <>
This fragment isn't needed

2023-08-21 09:35 UTC, sauravmaiti22 commented on packages/components/src/components/ui/BankRefundModal/BankRefundModal.tsx
> +            <div className="bg-white max-h-screen overflow-auto">
Yes they can be merged. I have made the changes to do that.

2023-08-21 09:35 UTC, sauravmaiti22 commented on packages/components/src/components/ui/molecules/Select/SelectAccount/SelectAccount.tsx
> +              <>
Removed it.

2023-08-21 09:39 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/32.

2023-08-21 14:55 UTC, pabloi-nf requested changes
Apply fixes on the image
![image](https://github.com/nofrixion/nofrixion.business/assets/127946572/ec6812da-91bb-490a-8ad2-2b58436dc0af)

2023-08-22 15:06 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/32.

2023-08-23 09:43 UTC, pabloi-nf commented
Thanks @sauravmaiti22 it all looks good. 
There is only one last thing I'm noticing, that is an extra space under the "to account" name
<img width="369" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/8741e408-2eb6-4bde-9d50-465339c2ea10">

If we remove that 0.5rem margin we are good.
Thanks

2023-08-23 09:44 UTC, pabloi-nf requested changes
Thanks @sauravmaiti22 it all looks good.
There is only one last thing I'm noticing, that is an extra space under the "to account" name
image

If we remove that 0.5rem margin we are good.
Thanks

2023-08-24 16:48 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/32.

2023-08-24 16:58 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/32.

2023-08-25 11:22 UTC, pabloi-nf approved these changes

2023-08-29 09:10 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/32.

2023-08-29 09:13 UTC, arifmatin approved these changes

2023-08-29 11:54 UTC, donalnofrixion approved these changes

2023-08-29 11:59 UTC, merged