[MOOV-2081]: Disabled Bitcion Lightning payment method
nofrixion/nofrixion.business pull request #33
Opened 2023-08-18 19:57 UTC by agranillonf

Temporarily disabled the Bitcoin Lightning payment method when creating payment requests.

2023-08-18 20:01 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/33.

2023-08-21 08:25 UTC, arifmatin approved these changes

2023-08-21 08:44 UTC, pabloi-nf requested changes
I don't know if this changed or if it was like this before, but it becomes more obvious now that the font size for the payment methods names are too big.
They have 1rem and they should have 0.875rem.

<img width="438" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/9c596e60-83a3-4c3b-a16e-70d35942a51f">

2023-08-21 14:49 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/33.

2023-08-21 15:44 UTC, pabloi-nf approved these changes

2023-08-21 16:08 UTC, merged