Feature/moov 2150 pending payments
nofrixion/nofrixion.business pull request #34
Opened 2023-08-21 09:32 UTC by arifmatin

Pending payments component that uses usePendingPayments hook to get data from the api.
Component is used in the account dashboard. 
Won't show the component if you don't have any pending payments. 

TODO: Animations

2023-08-21 09:36 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/34.

2023-08-21 09:41 UTC, arifmatin commented
![pending_payments](https://github.com/nofrixion/nofrixion.business/assets/92720032/83511601-ccac-459c-9550-c9d06bfb9640)

2023-08-21 09:51 UTC, sipsorcery approved these changes

2023-08-21 10:09 UTC, sauravmaiti22 requested changes

2023-08-21 10:09 UTC, sauravmaiti22 commented on packages/clients/src/types/ApiResponses.ts
> +  destinationAccountNumber: string
Use Destination property from Payout model instead which is of type Counterparty. These fields are deprecated.

2023-08-21 10:09 UTC, sauravmaiti22 commented on packages/clients/src/types/ApiResponses.ts
> +  userID: string
Make these properties nullable as they are nullable in Payout model.

2023-08-22 09:21 UTC, pabloi-nf requested changes
The arrow should point down when the list is closed
<img width="222" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/d362a375-5fc7-4f9c-9e8b-964e0fcbcf96">

The "See more" link should appear when there are more than 3 pending payments. Maybe instead of "See more" we should say "See all".
This link should have a hover state without the underline.

There should be a line between the last pending payment and the "See all" link.
<img width="389" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/4131e174-1aac-4eed-8dc9-cc1b644bc930">

2023-08-22 13:28 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/34.

2023-08-22 15:28 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/34.

2023-08-23 09:21 UTC, pabloi-nf approved these changes

2023-08-23 09:35 UTC, sauravmaiti22 approved these changes

2023-08-23 09:37 UTC, merged