[MOOV-2204]: Added payout metric tabs to dashboard
nofrixion/nofrixion.business pull request #53
Opened 2023-09-07 02:58 UTC by agranillonf

Depends on: MoneyMoov API PR #1208
Won't work until this PR is merged to develop.
------------------------------------------------

Added payout metric tabs to the payouts dashboard, with corresponding filter actions.

2023-09-07 03:02 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/53.

2023-09-07 06:24 UTC, donalnofrixion approved these changes

2023-09-07 09:04 UTC, pabloi-nf requested changes
I see 2 tabs with 0, but with entries

<img width="1640" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/afff5e00-24a9-4816-97c5-84bd329b8474">
<img width="1642" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/b1875e50-d3b4-4b52-a8e3-1e0f596f4876">

2023-09-07 14:23 UTC, pabloi-nf approved these changes

2023-09-07 18:59 UTC, agranillonf commented
@pabloi-nf MoneyMoov API has been deployed to develop, so this PR can now be fully tested.

2023-09-07 20:45 UTC, Publicker approved these changes

2023-09-07 20:45 UTC, Publicker commented on apps/business/src/pages/payouts/page.tsx
> +    <>
We could get rid of this Fragment.

2023-09-07 20:51 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/53.

2023-09-07 21:07 UTC, agranillonf commented
@donalnofrixion @Publicker re-requesting your approvals since the solution to Ticket #2235 (Payee sorting) is now included in this PR (won't work until MoneyMoov API PR #1211 is merged).

2023-09-07 21:09 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/53.

2023-09-08 07:14 UTC, donalnofrixion approved these changes

2023-09-08 08:37 UTC, pabloi-nf approved these changes

2023-09-08 11:32 UTC, Publicker approved these changes

2023-09-08 14:10 UTC, agranillonf commented
@pabloi-nf Re-requesting your review since you can now test Payee sorting.

2023-09-08 15:07 UTC, pabloi-nf approved these changes

2023-09-08 15:23 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/53.

2023-09-08 15:25 UTC, merged