Feature/moov 2205 payout details modal
nofrixion/nofrixion.business pull request #54
Opened 2023-09-07 14:47 UTC by donalnofrixion

Added the Payout details modal.

TODO:

1. Add support for tags
2. Wire up edit flow

2023-09-07 14:51 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/54.

2023-09-07 15:10 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/54.

2023-09-07 15:29 UTC, pabloi-nf requested changes
The style of the status labels need to be the same as in the payment requests.
I can see the same errors than in the list, with the icons vertically misaligned.

If some of the optional fields are not present we shouldn't show the title. In this case, the "description" title shouldn't be visible. 
<img width="401" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/9918bc98-6596-40b8-b50c-2af26f5cd9aa">



This is something I forgot on the design, but the amount needs to have the same style than in the PR details, with superscript decimals 

<img width="201" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/d78fd93f-1672-4b84-810c-8bee7d61c43d">
<img width="230" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/e0ff9203-c7c0-4d67-8903-0ddfcecdb9f5">

The font-size of the account names need to be 14px.
<img width="433" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/d398b0d5-83cf-40d0-bd1e-c15da8154ba4">

2023-09-07 16:10 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/54.

2023-09-07 16:16 UTC, donalnofrixion commented
Hi @pabloi-nf I've addressed your comments

2023-09-07 16:21 UTC, sipsorcery commented
I get a horizontal scroll bar which seems redundant.

![image](https://github.com/nofrixion/nofrixion.business/assets/197660/210ae406-dbe7-4be8-a2ef-0a3f7522765f)

2023-09-07 17:29 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/54.

2023-09-07 18:57 UTC, sipsorcery approved these changes

2023-09-07 20:43 UTC, Publicker commented on packages/components/src/components/ui/atoms/Icon/Icon.tsx
> +        stroke="#29A37A"
We try not to include the color in the stroke and use it when using the <Icon /> component as this would give us the possibility to change the color as in an easier way, such as in a hover state.

We try not to set a color for the stroke/fill and instead apply it to the `<Icon />` component. This method simplifies changing colours, especially makes it easier for states, such as hover.

Here's what happen when I try to change the color of all icons:
![Hover state](https://github.com/nofrixion/nofrixion.business/assets/52673485/1664b09f-8159-4127-aeab-7e3ab9ba1a3f)

`done/16`, `pending-approval/16` and `inprogress/12` seem to be the ones that don't adapt correctly.

2023-09-08 07:09 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/54.

2023-09-08 11:33 UTC, Publicker approved these changes

2023-09-08 12:50 UTC, pabloi-nf approved these changes

2023-09-08 14:06 UTC, merged