Add Account Name Update Functionality
nofrixion/nofrixion.business pull request #73
Opened 2023-09-20 13:55 UTC by Publicker

Once upon a time... in a realm not so far from this very codebase, a ticket arose. Its humble request? A mere account name update. But wow, it took longer than I thought (sorry about that!). Good news is, it's done now and you can change account names!

_(I hope this story makes up for the wait a little bit 😅)_

I've added a video to show how it works:

https://github.com/nofrixion/nofrixion.business/assets/52673485/eee71f46-b78e-489a-b942-58c3c7729c5f

2023-09-20 13:59 UTC, donalnofrixion approved these changes

2023-09-20 13:59 UTC, donalnofrixion commented on packages/clients/src/clients/AccountsClient.ts
> +   * TODO: Updates an Account
Remove the TODO?

2023-09-20 14:03 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/73.

2023-09-20 14:08 UTC, Publicker commented on packages/clients/src/clients/AccountsClient.ts
> +   * TODO: Updates an Account
Oopsy! Thanks

2023-09-20 14:12 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/73.

2023-09-20 14:13 UTC, sauravmaiti22 approved these changes

2023-09-20 16:02 UTC, pabloi-nf requested changes
We need to allow the user to discard the changes. This should happen if the user clicks outside the title or presses the ESC key

2023-09-20 17:55 UTC, donalnofrixion commented
> We need to allow the user to discard the changes. This should happen if the user clicks outside the title or presses the ESC key

@Publicker This is implemented here
https://github.com/nofrixion/nofrixion.business/blob/develop/packages/components/src/components/ui/Tags/AddTag/AddTag.tsx

2023-09-22 19:22 UTC, Publicker commented
> Looks good @Publicker
> 
> One question. I feel like clicking the edit icon should enter edit mode

@donalnofrixion Good idea! Done!

2023-09-22 19:23 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/73.

2023-09-23 05:33 UTC, donalnofrixion approved these changes

2023-09-23 05:33 UTC, donalnofrixion commented
🔥

2023-09-25 08:29 UTC, arifmatin approved these changes

2023-09-25 10:07 UTC, merged