[MOOV 2265] Connect external account
nofrixion/nofrixion.business pull request #74
Opened 2023-09-20 14:35 UTC by donalnofrixion

TODO:

1. Add context menu
2. Implement revoke connection
3. Implement renew connection
4. Banks icons

2023-09-20 14:42 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/74.

2023-09-20 14:49 UTC, sipsorcery requested changes

2023-09-20 14:49 UTC, sipsorcery commented on packages/components/src/components/ui/Modals/ConnectBankModal/ConnectBankModal.stories.tsx
> +      processor: PaymentProcessor.Plaid,
Should these be hardcoded? If so we aren't using Plaid anymore and the back end doens't know what to do with Plaid requests.

2023-09-20 14:54 UTC, donalnofrixion commented
https://github.com/nofrixion/nofrixion.business/assets/89344328/9dd27c8f-5866-43e2-a52d-beb1ee83fdc4

2023-09-20 14:56 UTC, arifmatin commented on packages/clients/src/types/Enums.ts
> +}
For account identification type. In the API we only support SORT_CODE, ACCOUNT_NUMBER, IBAN and BIC.  So I don't think we need the other options.

2023-09-20 14:57 UTC, donalnofrixion commented on packages/components/src/components/ui/Modals/ConnectBankModal/ConnectBankModal.stories.tsx
> +      processor: PaymentProcessor.Plaid,
That's just the StoryBook story

2023-09-20 14:58 UTC, donalnofrixion commented on packages/clients/src/types/Enums.ts
> +}
I mapped everything we had in our API for completeness.

2023-09-20 14:59 UTC, sipsorcery commented
> Screen.Recording.2023-09-20.at.15.53.23.mov

The video is great and all but completely overshadowed by the AMAZING feature of emojis in the account name!!!

2023-09-20 14:59 UTC, sipsorcery approved these changes

2023-09-20 15:01 UTC, arifmatin commented on packages/clients/src/types/Enums.ts
> +}
Oh ok. That's alright

2023-09-20 15:02 UTC, arifmatin approved these changes

2023-09-20 15:06 UTC, Publicker commented on packages/components/src/components/ui/atoms/Icon/Icon.tsx
We shouldn't include the `stroke` colours in here. That should be handled by the parent which uses the icon as it gives more control and customisation there.

2023-09-20 15:06 UTC, Publicker commented on packages/components/src/components/ui/utils/LayoutWrapper.tsx
> +  duration = 2.2,
Is this intended?

Not sure if there's any LayoutWrapper using the default duration, but this is a quite some difference on the animation if there's any.

2023-09-20 15:08 UTC, Publicker commented on packages/components/src/components/ui/atoms/AccountConnection/AccountConnection.tsx
> +        </div>
Button element if preferred if possible, as this would give accessibility features.

2023-09-20 15:08 UTC, Publicker commented
> > Screen.Recording.2023-09-20.at.15.53.23.mov
> 
> The video is great and all but completely overshadowed by the AMAZING feature of emojis in the account name!!!

😎😎😎

2023-09-20 15:09 UTC, donalnofrixion commented on packages/components/src/components/ui/utils/LayoutWrapper.tsx
> +  duration = 2.2,
> Is this intended?
> 
> Not sure if there's any LayoutWrapper using the default duration, but this is a quite some difference on the animation if there's any.

Sh*t!

2023-09-20 15:21 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/74.

2023-09-21 08:58 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/74.

2023-09-21 09:04 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/74.

2023-09-21 09:59 UTC, pabloi-nf requested changes
After pressing in "renew connection" this pop up should appear.
<img width="613" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/7b453139-9c1e-4e4e-85f9-a08d508489a2">


The transactions page is missing the logo and the "expires in" line.
<img width="432" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/c102bf98-1ea7-43ee-96e8-455a672fca22">


The "expires in" line on hover shouldn't change the color of the icon.
The "Renew connection" text link should have #00264D as text color, and a hover state without the underline.

<img width="298" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/15a5ac9c-ce39-41fd-9333-a765a3323330">


There is something about the pop ups. I can see all of them have a smaller padding-top now.
The padding-top of the H3 should be 1.5rem.
Also, the font-weight should be 600.

<img width="451" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/ba376d04-d7d4-4f92-8dfe-045ba657abf9">


It shows this error sometimes. What it means and what can we say that is more informative?
<img width="639" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/3fc69bc3-37d4-4c5f-8259-e52c0fda724d">


The amount lines have to be vertically aligned (same distance on top and bottom to the edge of the card).
Also, the numbers here shouldn't be tabular.
<img width="297" alt="image" src="https://github.com/nofrixion/nofrixion.business/assets/127946572/156930d5-b44c-4e4b-9fd5-63e81ae5c929">

2023-09-21 15:39 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/74.

2023-09-21 16:29 UTC, merged