Feature/moov 2297 context menu
nofrixion/nofrixion.business pull request #77
Opened 2023-09-25 12:39 UTC by donalnofrixion

2023-09-25 12:43 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/77.

2023-09-25 12:49 UTC, sipsorcery approved these changes

2023-09-25 12:53 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/77.

2023-09-25 13:38 UTC, Publicker requested changes
In addition to commenting on the code, I'll do my best to provide a comprehensive review, especially in Pablo's absence. Those are some big shoes to fill! (so I'll try my best).

- The 'Renew Connection' modal doesn't match the design. Comments here:
![Screenshot 2023-09-25 at 10 11 10](https://github.com/nofrixion/nofrixion.business/assets/52673485/accc3b73-e666-480e-ac1b-d0d96bde6a3f)



- The context menu modal doesn't open as smoothly as it's usual for the business portal. I believe it lacks the animation. It'd be awesome if it had the same or a similar animation to the one in the Payment Request table. Here's a video showcasing its current opening and closing:

https://github.com/nofrixion/nofrixion.business/assets/52673485/ca817e0a-6bd0-43be-9464-4b327fccb4ef

2023-09-25 13:38 UTC, Publicker commented on packages/components/src/components/ui/molecules/ConnectedAccountContextMenu/ConnectedAccountContextMenu.tsx
> +            onClick={(event) => event.stopPropagation()}
What's the difference between `onSelect` and `onClick`? I've noticed we use `stopPropagation` for both. What do you think about integrating `event.stopPropagation()` directly into `DropdownMenuItem`?

2023-09-25 13:38 UTC, Publicker commented on packages/components/src/components/ui/atoms/DropDown/DropDown.tsx
> +import { cn } from '../../../../../../../apps/business/src/lib/utils/utils'
Using `cn` from business in components seems wrong. I'd suggest to import it directly from the same project.

2023-09-25 17:11 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/77.

2023-09-25 18:23 UTC, Publicker requested changes
Animation is really nice! And spacing looks better. However, I noticed a few things:

- Regarding spacing and sizes:
![#77 - Review 2](https://github.com/nofrixion/nofrixion.business/assets/52673485/59ad5d82-bc6a-48c4-ac79-5b645122e67d)

- I believe the Privacy Policy should directly link to https://nofrixion.com/privacy-policy and open in a new tab.

- The changes to the dropdown have made the "Revoke" icon appear a bit off - almost like it's cropped or of lower quality.
![Revoke icon feedback](https://github.com/nofrixion/nofrixion.business/assets/52673485/125d3765-b2bc-4611-a7fb-cb77bc976c16)

- When cycling through the dropdown options ("Refresh" and "Revoke connection") with the keyboard, it doesn't trigger the "hover" state, unlike what happens in the Payment Request table. But it works fine with a regular hover.

2023-09-26 15:47 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/77.

2023-09-27 14:45 UTC, merged