[MOOV-2084]: Restored dynamic horizontal navigation menu
nofrixion/nofrixion.business pull request #82
Opened 2023-09-27 20:41 UTC by agranillonf

When on 1280px width or higher viewports, the original horizontal nav menu will be displayed.

Note: It'll be worth to test with long merchant names.

2023-09-27 20:46 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/82.

2023-09-28 07:30 UTC, donalnofrixion requested changes
The hover effect is missing from the items

2023-09-28 07:37 UTC, donalnofrixion requested changes

2023-09-28 07:37 UTC, donalnofrixion commented on apps/business/src/components/Navbar/NavbarItem.tsx
> +      href={href}
For react router to work properly you need to use navigate here. Clicking back in history is broken here.

2023-09-28 08:35 UTC, donalnofrixion commented on apps/business/src/components/Navbar/NavbarItem.tsx
> +      href={href}
If you replace the "<a>" with a react router "Link" component, you should be good.

`<Link
      to={href}
      className="relative text-xs px-4 pt-2 pb-2 flex items-center 2xl:text-sm 2xl:px-6"
    >
      <div className="w-4 h-4">
        <img src={leftIcon} alt={`${label} icon`} />
      </div>

      <span className="ml-3">{label}</span>

      {isActive && <div className="h-1 bg-nav-accent w-full absolute left-0 bottom-0"></div>}
    </Link>`

2023-09-28 16:10 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/82.

2023-09-29 07:39 UTC, donalnofrixion commented
Is it just me or does the font size on desktop feel a little small?

Also, I think we should have a hover effect on the items.

2023-09-29 19:47 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/82.

2023-10-02 08:03 UTC, donalnofrixion commented
Looks much better Axel. 
One last thing. I think the selected option should remain highlighted and the link should not be clickable.

2023-10-02 15:15 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/82.

2023-10-02 15:18 UTC, donalnofrixion approved these changes

2023-10-03 14:50 UTC, arifmatin approved these changes

2023-10-03 20:03 UTC, merged