[MOOV-2174]: Added PaymentAttempts column to PR table
nofrixion/nofrixion.business pull request #84
Opened 2023-10-03 09:34 UTC by agranillonf

Depends on https://github.com/nofrixion/moneymoov-dotnet/pull/201 to fully work.

------------------------

Added a column to the payment request table that summarises payment attempts of each record.

2023-10-03 09:38 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/84.

2023-10-03 10:17 UTC, donalnofrixion requested changes
We no longer use svgs directly. There is an "Icon" component which can be updated to include the new icons.

2023-10-03 10:45 UTC, sauravmaiti22 commented on packages/components/src/components/ui/PaymentRequestDetails/PaymentRequestDetails.tsx
> +                paymentRequest.paymentAttempts.filter((pa) => pa.paymentStatus === 'received'),
We can start using the properties that you added to PaymentRequest model. This should be calculated as AmountReceived-AmountRefunded

2023-10-03 10:52 UTC, sauravmaiti22 commented on packages/components/src/utils/parsers.ts
> +      !remotePaymentAttempt.authorisedAt &&
These conditions imply that the payment attempt is just initiated and not received. Why is the status set to received?

2023-10-04 14:32 UTC, sauravmaiti22 commented on packages/components/src/utils/parsers.ts
> +      !remotePaymentAttempt.authorisedAt &&
If authorisedAt is not null that means the pisp payment was authorised by the customer and the money is pending settlement. So if settledAt is null but authorisedAt is not null, the status should be pending.

2023-10-05 08:54 UTC, donalnofrixion requested changes

2023-10-05 08:54 UTC, donalnofrixion commented on packages/components/src/components/ui/PaymentRequestTable/PaymentRequestTable.tsx
> +                    setAmountSortDirection && setAmountSortDirection(sortDirection)
I think this sort should be removed

2023-10-05 09:20 UTC, sauravmaiti22 requested changes

2023-10-05 09:20 UTC, sauravmaiti22 commented on packages/components/src/utils/parsers.ts
> +
@agranillonf The status can change from pending to failed when settleFailedAt is not null. I would suggest using the PaymentAttempt Status to determine pending status. If the status is Authorized then it is pending, no need to calculate the state here. If the status is none and settleFailedAt || cardAuthoriseFailedAt || cardAuthenticationSetupFailedAt is not null then return failed. Otherwise return received.

2023-10-05 19:02 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/84.

2023-10-05 19:07 UTC, donalnofrixion approved these changes

2023-10-06 09:02 UTC, sauravmaiti22 requested changes

2023-10-06 09:02 UTC, sauravmaiti22 commented on packages/components/src/utils/parsers.ts
> +          !remotePaymentAttempt.settledAt))
This condition is unnecessary. settleFailedAt checks if settle failed.

2023-10-06 11:11 UTC, sauravmaiti22 approved these changes

2023-10-06 14:30 UTC, sipsorcery commented
Latest changes for this PR can be tested at https://business-dev.nofrixion.com/84.

2023-10-06 14:40 UTC, merged